### ISSUE TITLE
Implement available query parameters of the current data model

### ISSUE THREAD

**Issue by surchs** [neurobagel/bagelapi#31]
The new API should provide query parameters for the variables our data model currently supports. This Epic will track the progress towards implementing each query parameter.

- [x] https://github.com/neurobagel/bagelapi/issues/26
- [x] https://github.com/neurobagel/bagelapi/issues/15
- [x] #32
- [x] https://github.com/neurobagel/bagelapi/issues/23
- [x] #33
- [x] #34
